repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        - id: check-yaml
          args: [--unsafe]
          exclude: '.*templates.*.yaml'
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-ast
    - repo: https://github.com/gruntwork-io/pre-commit
      rev: v0.1.5
      hooks:
        - id: terraform-fmt
        - id: terraform-validate
        - id: tflint
        - id: shellcheck
    - repo: https://github.com/psf/black
      rev: 19.3b0
      hooks:
        - id: black
